spring:
  application:
    name: lunchExpedition
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lunchExpedition
    username: heejun
    password: 0328
mybatis:
  mapper-locations: classpath:mappers/*.xml